spring.application.name=Project_HSF302_Group2

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=coffee_shop;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456

# Hibernate ddl-auto (update để tự động tạo bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
