
spring.application.name=Project_HSF302_Group2

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=coffee_shop;encrypt=true;trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

logging.level.hsf302.se2033jv=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

server.port=8080
server.servlet.context-path=/
server.error.include-stacktrace=never
server.error.include-message=always

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.messages.basename=messages

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tailocshoptm@gmail.com
spring.mail.password=amlqpwtcusnllouv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.messages.encoding=UTF-8
spring.mail.default-encoding=UTF-8